Family Page HIFI
benson-fm/FUSION-Website pull request #36
Opened 2024-08-04 03:50 UTC by amlimjoc

2024-08-06 05:45 UTC, benson-fm requested changes
Great job Arvin! Just minor changes to do!

2024-08-06 05:45 UTC, benson-fm commented on src/pages/ProgramsPage/FamilyPage/FamilyNavbar.jsx
theres a navbar that exists in components that you can utilize, i know during the time of developing this it wasn't nice looking but just for future reference use that one!

2024-08-06 05:45 UTC, benson-fm commented on src/pages/ProgramsPage/FamilyPage/FamilyNavbar.jsx
> +      <div className="relative">
make this cover the whole screen so you would add somethign like h-screen

2024-08-06 05:45 UTC, benson-fm commented on src/pages/ProgramsPage/FamilyPage/WhatIsFam.jsx
> +            <div ref={ref} className={`flex flex-col items-center justify-center w-[816px] h-[258px] transition-opacity ease-in duration-700 ${isVisible ? "opacity-100" : "opacity-0"}`}>
Add some more padding for the top and the bottom

2024-08-06 05:45 UTC, benson-fm commented on src/pages/ProgramsPage/FamilyPage/OrangeFam.jsx
> +                <div className={`border-t border-[#FAC80A] w-[115px] border-[2px] mr-2 transition-opacity duration-700 ease-in-out ${isVisible ? 'opacity-100' : 'opacity-0'}`}></div>
for these lines make them a bit longer like in figma

2024-08-06 05:45 UTC, benson-fm commented on src/pages/ProgramsPage/FamilyPage/OrangeFam.jsx
> +      <h2 className="mt-4 text-2xl font-bold text-white">{title}</h2>
Make this less bold more thin like in the figma

2024-08-06 05:45 UTC, benson-fm commented on src/pages/ProgramsPage/FamilyPage/OrangeFam.jsx
> +            <p className={`font-inter mt-4 text-center w-[50rem] font-[400] text-[16px] leading-8 transition-opacity duration-700 ease-in-out ${isVisible ? 'opacity-100' : 'opacity-0'}`}>
make the width of this text a little longer so we can get that effect on the figma with the first line being longer than the other

2024-08-10 23:05 UTC, amlimjoc commented
closes #36

2024-08-10 23:05 UTC, closed without merging